# Generated by Django 5.0.3 on 2024-04-02 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_id', models.AutoField(primary_key=True, serialize=False)),
                ('companyName', models.CharField(max_length=50)),
                ('companyLocation', models.CharField(max_length=100)),
                ('companyAbout', models.TextField(max_length=100)),
                ('companyType', models.CharField(choices=[('IT', 'IT'), ('Non IT', 'Non IT')], max_length=100)),
                ('companyActive', models.BooleanField(default=False)),
            ],
        ),
    ]
