# Generated by Django 5.0.3 on 2024-04-02 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employeeName', models.CharField(max_length=50)),
                ('employeeEmail', models.EmailField(max_length=254)),
                ('employeeAddress', models.CharField(max_length=200)),
                ('employeeContact', models.IntegerField(max_length=10)),
                ('employeeAbout', models.TextField()),
                ('companyDetails', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.company')),
            ],
        ),
    ]
